//! The `?` help screen entries, shared with the language-gate corpus so
//! the help templates are verified by check-text like every other message
//! family (see GLOSSARY.md "Webpage" notes and lang::corpus).
//!
//! Tuple: (key char, speak-template description, printed on the help screen).

pub const HELP_ENTRIES: &[(char, &str, bool)] = &[
    ('?', "\tpokazati pomoć", true),
    ('/', "\topoznati znak", true),
    ('h', "\tvlěvo", true),
    ('j', "\tdolu", true),
    ('k', "\tgorě", true),
    ('l', "\tvpravo", true),
    ('y', "\tgorě i vlěvo", true),
    ('u', "\tgorě i vpravo", true),
    ('b', "\tdolu i vlěvo", true),
    ('n', "\tdolu i vpravo", true),
    ('H', "\tběgati vlěvo", false),
    ('J', "\tběgati dolu", false),
    ('K', "\tběgati gorě", false),
    ('L', "\tběgati vpravo", false),
    ('Y', "\tběgati gorě i vlěvo", false),
    ('U', "\tběgati gorě i vpravo", false),
    ('B', "\tběgati dolu i vlěvo", false),
    ('N', "\tběgati dolu i vpravo", false),
    ('\u{8}', "\tběgati vlěvo do ⟨n:prěškoda:gen⟩", false),
    ('\u{a}', "\tběgati dolu do ⟨n:prěškoda:gen⟩", false),
    ('\u{b}', "\tběgati gorě do ⟨n:prěškoda:gen⟩", false),
    ('\u{c}', "\tběgati vpravo do ⟨n:prěškoda:gen⟩", false),
    ('\u{19}', "\tběgati gorě i vlěvo do ⟨n:prěškoda:gen⟩", false),
    (
        '\u{15}',
        "\tběgati gorě i vpravo do ⟨n:prěškoda:gen⟩",
        false,
    ),
    ('\u{2}', "\tběgati dolu i vlěvo do ⟨n:prěškoda:gen⟩", false),
    ('\u{e}', "\tběgati dolu i vpravo do ⟨n:prěškoda:gen⟩", false),
    (
        '\0',
        "\t<SHIFT><dir>: běgati v ⟨toj:acc:f⟩ ⟨n:stråna:acc⟩",
        true,
    ),
    ('\0', "\t<CTRL><dir>: běgati do ⟨n:prěškoda:gen⟩", true),
    (
        'f',
        "<dir>\tboriti sę do ⟨n:smŕť:gen⟩ ili skoro do ⟨n:smŕť:gen⟩",
        true,
    ),
    ('t', "<dir>\tmetnųti něčto", true),
    ('m', "<dir>\tidti i ⟨ničto:gen⟩ ne vzęti", true),
    ('z', "<dir>\tužiti žezlo", true),
    ('^', "<dir>\topoznati vid ⟨n:pasť:gen⟩", true),
    (
        's',
        "\tiskati pasť/⟨a:tajny:dvėri:acc:pl⟩ ⟨n:dvėri:acc:pl⟩",
        true,
    ),
    ('>', "\tidti dolu", true),
    ('<', "\tidti gorě", true),
    ('.', "\tčekati jedin hod", true),
    (',', "\tvzęti něčto", true),
    ('i', "\tpokazati ⟨n:torba:acc⟩", true),
    ('I', "\tpokazati jedin prědmet", true),
    ('q', "\tpiti napitȯk", true),
    ('r', "\tčitati svitȯk", true),
    ('e', "\tjesti ⟨n:jeda:acc⟩", true),
    ('w', "\tdŕžati orųžje", true),
    ('W', "\tnositi ⟨n:brȯnja:acc⟩", true),
    ('T', "\tsjęti ⟨n:brȯnja:acc⟩", true),
    ('P', "\tnaděti pŕstenj", true),
    ('R', "\tsjęti pŕstenj", true),
    ('d', "\tostaviti prědmet", true),
    ('c', "\tnazvati prědmet", true),
    (
        'a',
        "\tpovtoriti ⟨a:poslědnji:komanda:acc⟩ ⟨n:komanda:acc⟩",
        true,
    ),
    (')', "\tpokazati orųžje v ⟨n:rųka:loc⟩", true),
    (']', "\tpokazati ⟨n:brȯnja:acc⟩", true),
    ('=', "\tpokazati ⟨n:pŕstenj:acc:pl⟩", true),
    ('@', "\tpokazati ⟨a:tvoj:stańje:acc⟩ ⟨n:stańje:acc⟩", true),
    ('D', "\tpokazati, čto uže ⟨v2:znati⟩", true),
    ('o', "\tpokazati/měnjati ⟨n:opcija:acc:pl⟩", true),
    ('\u{12}', "\tobnoviti ekran", true),
    (
        '\u{10}',
        "\tpovtoriti ⟨a:poslědnji:sȯobčeńje:acc⟩ ⟨n:sȯobčeńje:acc⟩",
        true,
    ),
    (
        '\u{1b}',
        "\tanulovati ⟨n:komanda:acc⟩, ^[ jest knopka escape",
        true,
    ),
    ('S', "\tshråniti ⟨n:igra:acc⟩", true),
    ('Q', "\tizhod", true),
    ('!', "\totvoriti shell", true),
    ('F', "<dir>\tboriti sę dokolě někto ne ⟨v3:umrěti⟩", true),
    (
        'v',
        "\tpokazati ⟨n:verzija:acc⟩, izdańje, čislo ⟨n:temnica:gen⟩",
        true,
    ),
];
